// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkUMAF8HDNKgBxC28-c4VrBuWSu3UMkgE',
    appId: '1:732681672818:web:7a13339d88552d58c94aeb',
    messagingSenderId: '732681672818',
    projectId: 'staffservicemanagement',
    authDomain: 'staffservicemanagement.firebaseapp.com',
    storageBucket: 'staffservicemanagement.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZGSSxDBQ-X3fMtKIZkiFjklqS1nw8fec',
    appId: '1:732681672818:android:c677869878fe65edc94aeb',
    messagingSenderId: '732681672818',
    projectId: 'staffservicemanagement',
    storageBucket: 'staffservicemanagement.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5PYgxMEpClyIBfyliLnZIRPh_6xcdKkY',
    appId: '1:732681672818:ios:4e5cc595b34ae0e4c94aeb',
    messagingSenderId: '732681672818',
    projectId: 'staffservicemanagement',
    storageBucket: 'staffservicemanagement.firebasestorage.app',
    iosBundleId: 'com.example.staffServiceManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkUMAF8HDNKgBxC28-c4VrBuWSu3UMkgE',
    appId: '1:732681672818:web:65675c1b8dc4fc67c94aeb',
    messagingSenderId: '732681672818',
    projectId: 'staffservicemanagement',
    authDomain: 'staffservicemanagement.firebaseapp.com',
    storageBucket: 'staffservicemanagement.firebasestorage.app',
  );
}
